name: Generate GitHub Contributions Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: venvVarun
          outputs: |
              dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
              dist/github-snake.svg
              dist/github-snake-dark.svg?palette=github-dark
      # - palette:      A preset of color, one of [github, github-dark, github-light]
      # - color_snake:  Color of the snake
      # - color_dots:   Coma separated list of dots color. 
      #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
      #                 Exactly 5 colors are expected.
      # outputs: |
      #     dark.svg?palette=github-dark&color_snake=blue
      #     light.svg?color_snake=#7845ab
      #     ocean.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
